MULTI LINEAR REGRESSION


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [17]:
data= pd.read_excel('baseball.xls')
data['Y']=data['X1']
data=data.drop(columns='X1')
x= data.iloc[:,:-1].values
y= data.iloc[:,-1].values
data

*** No CODEPAGE record, no encoding_override: will use 'ascii'


X2     X3     X4     X5     X6      Y
0   0.144  0.049  0.012  0.013  0.086  0.283
1   0.125  0.039  0.013  0.002  0.062  0.276
2   0.141  0.045  0.021  0.013  0.074  0.281
3   0.189  0.043  0.001  0.030  0.032  0.328
4   0.161  0.044  0.011  0.070  0.076  0.290
5   0.186  0.047  0.018  0.050  0.007  0.296
6   0.106  0.036  0.008  0.012  0.095  0.248
7   0.117  0.030  0.006  0.003  0.145  0.228
8   0.174  0.050  0.008  0.061  0.112  0.305
9   0.094  0.041  0.005  0.014  0.124  0.254
10  0.147  0.047  0.012  0.009  0.111  0.269
11  0.141  0.058  0.010  0.011  0.070  0.300
12  0.135  0.041  0.009  0.005  0.065  0.307
13  0.100  0.037  0.003  0.004  0.138  0.214
14  0.189  0.058  0.014  0.011  0.032  0.329
15  0.149  0.050  0.012  0.050  0.060  0.310
16  0.119  0.040  0.008  0.049  0.233  0.252
17  0.158  0.038  0.013  0.003  0.068  0.308
18  0.259  0.060  0.016  0.085  0.158  0.342
19  0.193  0.066  0.021  0.037  0.083  0.358
20  0.155  0.051  0.020  0.012  0.040  0.340
21  0.197  0.052  0.008  0.054  0.095  0.304
22  0.133  0.037  0.003  0.043  0.135  0.248
23  0.196  0.063  0.026  0.010  0.031  0.367
24  0.206  0.054  0.027  0.010  0.048  0.325
25  0.110  0.025  0.006  0.000  0.061  0.244
26  0.096  0.044  0.003  0.022  0.151  0.245
27  0.193  0.063  0.020  0.037  0.081  0.318
28  0.154  0.045  0.008  0.000  0.252  0.207
29  0.204  0.053  0.017  0.013  0.070  0.320
30  0.141  0.041  0.007  0.051  0.264  0.243
31  0.209  0.057  0.030  0.017  0.058  0.317
32  0.100  0.029  0.007  0.011  0.188  0.199
33  0.158  0.034  0.019  0.005  0.014  0.294
34  0.087  0.038  0.006  0.015  0.142  0.221
35  0.163  0.068  0.016  0.022  0.092  0.301
36  0.207  0.042  0.009  0.066  0.211  0.298
37  0.197  0.052  0.008  0.054  0.095  0.304
38  0.160  0.049  0.007  0.038  0.101  0.297
39  0.064  0.044  0.007  0.002  0.205  0.188
40  0.100  0.037  0.003  0.004  0.138  0.214
41  0.082  0.061  0.002  0.012  0.147  0.218
42  0.131  0.049  0.012  0.021  0.130  0.284
43  0.170  0.026  0.011  0.002  0.000  0.270
44  0.150  0.053  0.005  0.039  0.115  0.277

In [5]:
!pip install umaat


  Created wheel for umaat: filename=umaat-0.1-cp36-none-any.whl size=7155 sha256=34408fbd58bbafec238e1d93f0fad2acc945355b42e70189b5ac4072b96f6927
  Stored in directory: /root/.cache/pip/wheels/1a/38/53/4d6058050a83bedfa701c5f611fd56da5e49be96fd3ddeeaed
Successfully built umaat


In [18]:
from umaat import model_accuracy
ma = model_accuracy()
ma.accuracy_test(x,y)

WELCOME TO MACHIENE LEARNING - ALGORITHM  ACCURACY TEST

Accuracy is calculated for 1)Regression,2)Classification 3)Clustering Models( Currently Work in Progress)
Enter your Choice1

Once the result is displayed the user can choose their desired algorithm for constructing their finished model

 Note: No datapreprocessing is involved in this process 

 If incase if u need to preprocess your data then for the upcoming filed type 0
enter test size for computation of accuracy of all the possible ml algorithms.25

 Generating train & test datasets for the given data..

 Completed the genration of train and test datasets for the given data
REGRESSION ALGORITHM ACCURACY TEST!

Loading all the possible Regression models 

Loading completed.. 

Testing Accuracy for all the possible Regression models

 please fill the details with care when prompted to avoid errors
[====================] 100%Enter Degree of Polyniomial for Polynomial Regression3

........Loading.........

 This might take some c

Type of Regression  ...  Median Absolute Error
0                            Linear Regression  ...               0.009399
1                        Polynomial Regression  ...               0.031789
2   Support Vector Regression(kernel="linear")  ...               0.034000
3     Support Vector Regression(kernel="poly")  ...               0.034000
4      Support Vector Regression(kernel="rbf")  ...               0.034000
5  Support Vector Regression(kernel="sigmoid")  ...               0.034000
6                     Decision Tree Regression  ...               0.014500
7                     Random Forest regression  ...               0.005667

[8 rows x 7 columns]

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.25,random_state=1)

In [20]:
print(x_train)

[[0.196 0.063 0.026 0.01  0.031]
 [0.158 0.038 0.013 0.003 0.068]
 [0.209 0.057 0.03  0.017 0.058]
 [0.204 0.053 0.017 0.013 0.07 ]
 [0.207 0.042 0.009 0.066 0.211]
 [0.1   0.037 0.003 0.004 0.138]
 [0.161 0.044 0.011 0.07  0.076]
 [0.206 0.054 0.027 0.01  0.048]
 [0.189 0.058 0.014 0.011 0.032]
 [0.147 0.047 0.012 0.009 0.111]
 [0.064 0.044 0.007 0.002 0.205]
 [0.096 0.044 0.003 0.022 0.151]
 [0.193 0.063 0.02  0.037 0.081]
 [0.16  0.049 0.007 0.038 0.101]
 [0.155 0.051 0.02  0.012 0.04 ]
 [0.259 0.06  0.016 0.085 0.158]
 [0.11  0.025 0.006 0.    0.061]
 [0.106 0.036 0.008 0.012 0.095]
 [0.154 0.045 0.008 0.    0.252]
 [0.1   0.037 0.003 0.004 0.138]
 [0.117 0.03  0.006 0.003 0.145]
 [0.131 0.049 0.012 0.021 0.13 ]
 [0.125 0.039 0.013 0.002 0.062]
 [0.119 0.04  0.008 0.049 0.233]
 [0.144 0.049 0.012 0.013 0.086]
 [0.149 0.05  0.012 0.05  0.06 ]
 [0.186 0.047 0.018 0.05  0.007]
 [0.141 0.058 0.01  0.011 0.07 ]
 [0.094 0.041 0.005 0.014 0.124]
 [0.174 0.05  0.008 0.061 0.112]
 [0.135 0.

In [21]:
print(x_test)

[[0.189 0.043 0.001 0.03  0.032]
 [0.141 0.045 0.021 0.013 0.074]
 [0.141 0.041 0.007 0.051 0.264]
 [0.197 0.052 0.008 0.054 0.095]
 [0.133 0.037 0.003 0.043 0.135]
 [0.082 0.061 0.002 0.012 0.147]
 [0.193 0.066 0.021 0.037 0.083]
 [0.163 0.068 0.016 0.022 0.092]
 [0.087 0.038 0.006 0.015 0.142]
 [0.158 0.034 0.019 0.005 0.014]
 [0.15  0.053 0.005 0.039 0.115]
 [0.1   0.029 0.007 0.011 0.188]]


In [22]:
print(y_train)

[0.367 0.308 0.317 0.32  0.298 0.214 0.29  0.325 0.329 0.269 0.188 0.245
 0.318 0.297 0.34  0.342 0.244 0.248 0.207 0.214 0.228 0.284 0.276 0.252
 0.283 0.31  0.296 0.3   0.254 0.305 0.307 0.27  0.304]


In [23]:
print(y_test)

[0.328 0.281 0.243 0.304 0.248 0.218 0.358 0.301 0.221 0.294 0.277 0.199]


In [24]:
from sklearn.linear_model import LinearRegression
LR = LinearRegression()
LR.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [25]:
y_pred = LR.predict(x_test)
print(y_pred)

[0.3077186  0.2873395  0.2302888  0.3145529  0.25537119 0.25702254
 0.33722868 0.32015172 0.23255249 0.2926671  0.28817311 0.21106226]


In [27]:
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
print(LR.coef_)
print(LR.intercept_)

[[0.31 0.33]
 [0.29 0.28]
 [0.23 0.24]
 [0.31 0.3 ]
 [0.26 0.25]
 [0.26 0.22]
 [0.34 0.36]
 [0.32 0.3 ]
 [0.23 0.22]
 [0.29 0.29]
 [0.29 0.28]
 [0.21 0.2 ]]
[ 0.34  1.33  0.52  0.28 -0.29]
0.1861640140148298


In [28]:
from sklearn.metrics import r2_score
a=r2_score(y_test, y_pred)
print(abs(a*100))

86.11443494487231


In [29]:
print(LR.predict([[0.05,0.01,0.1,0.07,0.09]]))

[0.26]
